### PR TITLE
Avoid variable-sized object

### LINKED ISSUE #167: Variable-sized object initialization error in indigo
Today, I cloned this repo to catkin workspace in Ubuntu14.04 (indigo) and tried to compile.
However, building is failed due to variable-sized object initialization error.
Whole error log is as follows:
```
$ catkin build
-------------------------------------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/pazeshun/apc_ws/devel:/home/pazeshun/catkin_ws/devel:/opt/ros/indigo
Workspace:                   /home/pazeshun/dynamixel_test_ws
Source Space:       [exists] /home/pazeshun/dynamixel_test_ws/src
Build Space:        [exists] /home/pazeshun/dynamixel_test_ws/build
Devel Space:        [exists] /home/pazeshun/dynamixel_test_ws/devel
Install Space:     [missing] /home/pazeshun/dynamixel_test_ws/install
DESTDIR:                     None
-------------------------------------------------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
-------------------------------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
-------------------------------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------------------------------------------- 
Found '7' packages in 0.0 seconds. 
Starting ==> dynamixel_workbench                                                                                                                                                               
Starting ==> dynamixel_workbench_msgs                                                                                                                                                          
Starting ==> dynamixel_workbench_toolbox                                                                                                                                                       
Finished <== dynamixel_workbench                    [ 1.2 seconds ]                                                                                                                            
Finished <== dynamixel_workbench_toolbox            [ 1.9 seconds ]                                                                                                                            
Finished <== dynamixel_workbench_msgs               [ 6.5 seconds ]                                                                                                                            
Starting ==> dynamixel_workbench_operators                                                                                                                                                     
Starting ==> dynamixel_workbench_controllers                                                                                                                                                   
Starting ==> dynamixel_workbench_single_manager                                                                                                                                                
Starting ==> dynamixel_workbench_single_manager_gui                                                                                                                                            
Finished <== dynamixel_workbench_operators          [ 8.9 seconds ]                                                                                                                            
                                                                                                                                                                                               
[dynamixel_workbench_single_manager] ==> '/home/pazeshun/dynamixel_test_ws/build/dynamixel_workbench_single_manager/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' in '/home/pazeshun/dynamixel_test_ws/build/dynamixel_workbench_single_manager'
Scanning dependencies of target rosgraph_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_py
Scanning dependencies of target dynamixel_workbench_msgs_generate_messages_lisp
[  0%] Built target dynamixel_workbench_msgs_generate_messages_lisp
Scanning dependencies of target dynamixel_workbench_msgs_generate_messages_py
[  0%] Built target dynamixel_workbench_msgs_generate_messages_py
Scanning dependencies of target roscpp_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_lisp
Scanning dependencies of target roscpp_generate_messages_py
[  0%] Built target roscpp_generate_messages_py
Scanning dependencies of target dynamixel_workbench_msgs_generate_messages_eus
[  0%] Built target dynamixel_workbench_msgs_generate_messages_eus
Scanning dependencies of target roscpp_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_cpp
Scanning dependencies of target std_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
Scanning dependencies of target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_lisp
Scanning dependencies of target std_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_cpp
Scanning dependencies of target dynamixel_workbench_msgs_generate_messages_cpp
[  0%] Built target dynamixel_workbench_msgs_generate_messages_cpp
Scanning dependencies of target rosgraph_msgs_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_cpp
Scanning dependencies of target rosgraph_msgs_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_lisp
Scanning dependencies of target single_dynamixel_controller
[ 50%] Building CXX object CMakeFiles/single_dynamixel_controller.dir/src/single_dynamixel_controller.cpp.o
Linking CXX executable /home/pazeshun/dynamixel_test_ws/devel/lib/dynamixel_workbench_single_manager/single_dynamixel_controller
[ 50%] Built target single_dynamixel_controller
Scanning dependencies of target single_dynamixel_monitor
[100%] Building CXX object CMakeFiles/single_dynamixel_monitor.dir/src/single_dynamixel_monitor.cpp.o
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::AX():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:625:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::RX():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:730:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::MX():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:835:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::MXExt():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:944:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::MX2():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:1059:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::MX2Ext():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:1198:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::EX():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:1341:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::XL320():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:1450:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::XL():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:1551:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::XM():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:1690:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::XMExt():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:1833:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::XH():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:1982:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::PRO():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:2125:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp: In member function void single_dynamixel_monitor::SingleDynamixelMonitor::PROExt():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_single_manager/src/single_dynamixel_monitor.cpp:2246:84: error: variable-sized object getAllRegisteredData may not be initialized
   uint8_t getAllRegisteredData[last_register_addr+last_register_addr_length] = {0, };
                                                                                    ^
make[2]: *** [CMakeFiles/single_dynamixel_monitor.dir/src/single_dynamixel_monitor.cpp.o]  1
make[1]: *** [CMakeFiles/single_dynamixel_monitor.dir/all]  2
make: *** [all]  2
[dynamixel_workbench_single_manager] <== '/home/pazeshun/dynamixel_test_ws/build/dynamixel_workbench_single_manager/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2'
                                                                                                                                                                                                
Failed   <== dynamixel_workbench_single_manager     [ 9.4 seconds ]                                                                                                                            
                                                                                                                                                                                               
[dynamixel_workbench_controllers] ==> '/home/pazeshun/dynamixel_test_ws/build/dynamixel_workbench_controllers/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' in '/home/pazeshun/dynamixel_test_ws/build/dynamixel_workbench_controllers'
Scanning dependencies of target rosgraph_msgs_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_lisp
Scanning dependencies of target dynamixel_workbench_msgs_generate_messages_eus
[  0%] Built target dynamixel_workbench_msgs_generate_messages_eus
Scanning dependencies of target dynamixel_workbench_msgs_generate_messages_lisp
[  0%] Built target dynamixel_workbench_msgs_generate_messages_lisp
Scanning dependencies of target rosgraph_msgs_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_cpp
Scanning dependencies of target roscpp_generate_messages_py
[  0%] Built target roscpp_generate_messages_py
Scanning dependencies of target roscpp_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_lisp
Scanning dependencies of target roscpp_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_cpp
Scanning dependencies of target sensor_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_lisp
Scanning dependencies of target sensor_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_cpp
Scanning dependencies of target sensor_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_py
Scanning dependencies of target dynamixel_workbench_msgs_generate_messages_py
[  0%] Built target dynamixel_workbench_msgs_generate_messages_py
Scanning dependencies of target std_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_cpp
Scanning dependencies of target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_lisp
Scanning dependencies of target geometry_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_cpp
Scanning dependencies of target std_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
Scanning dependencies of target dynamixel_workbench_msgs_generate_messages_cpp
[  0%] Built target dynamixel_workbench_msgs_generate_messages_cpp
Scanning dependencies of target geometry_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
Scanning dependencies of target geometry_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_py
Scanning dependencies of target rosgraph_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_py
Scanning dependencies of target multi_port
[ 25%] Building CXX object CMakeFiles/multi_port.dir/src/multi_port.cpp.o
Linking CXX executable /home/pazeshun/dynamixel_test_ws/devel/lib/dynamixel_workbench_controllers/multi_port
[ 25%] Built target multi_port
Scanning dependencies of target position_control
[ 50%] Building CXX object CMakeFiles/position_control.dir/src/position_control.cpp.o
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_controllers/src/position_control.cpp: In member function void PositionControl::jointStatePublish():
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_controllers/src/position_control.cpp:118:44: error: variable-sized object present_position may not be initialized
   int32_t present_position[dxl_cnt_] = {0, };
                                            ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_controllers/src/position_control.cpp:123:44: error: variable-sized object present_velocity may not be initialized
   int32_t present_velocity[dxl_cnt_] = {0, };
                                            ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_controllers/src/position_control.cpp: In member function void PositionControl::goalJointPositionCallback(const ConstPtr&):
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_controllers/src/position_control.cpp:176:42: error: variable-sized object goal_position may not be initialized
   double goal_position[dxl_cnt_] = {0.0, };
                                          ^
/home/pazeshun/dynamixel_test_ws/src/dynamixel-workbench/dynamixel_workbench_controllers/src/position_control.cpp:181:45: error: variable-sized object goal_dxl_position may not be initialized
   int32_t goal_dxl_position[dxl_cnt_] = {0, };
                                             ^
make[2]: *** [CMakeFiles/position_control.dir/src/position_control.cpp.o]  1
make[1]: *** [CMakeFiles/position_control.dir/all]  2
make: *** [all]  2
[dynamixel_workbench_controllers] <== '/home/pazeshun/dynamixel_test_ws/build/dynamixel_workbench_controllers/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2'
                                                                                                                                                                                                
Failed   <== dynamixel_workbench_controllers        [ 9.7 seconds ]                                                                                                                            
Finished <== dynamixel_workbench_single_manager_gui [ 14.9 seconds ]                                                                                                                           
[build] There were '2' errors:                                                                                                                                                                 

Failed to build package 'dynamixel_workbench_single_manager' because the following command:

# Command to reproduce:
cd /home/pazeshun/dynamixel_test_ws/build/dynamixel_workbench_single_manager && /home/pazeshun/dynamixel_test_ws/build/dynamixel_workbench_single_manager/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j; cd -

# Path to log:
cat /home/pazeshun/dynamixel_test_ws/build/build_logs/dynamixel_workbench_single_manager.log

Exited with return code: 2 

Failed to build package 'dynamixel_workbench_controllers' because the following command:

# Command to reproduce:
cd /home/pazeshun/dynamixel_test_ws/build/dynamixel_workbench_controllers && /home/pazeshun/dynamixel_test_ws/build/dynamixel_workbench_controllers/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j; cd -

# Path to log:
cat /home/pazeshun/dynamixel_test_ws/build/build_logs/dynamixel_workbench_controllers.log

Exited with return code: 2 
                                                                                                                                                                                               
[build] Runtime: 21.5 seconds 
```

### PR DESCRIPTION
**Pull request by pazeshun**
Fixes #167

### CODE REVIEW

**Comment by pazeshun** [comment]
I think we shouldn't use variable length array (VLA) due to the following reasons:
- Some compilers support it and others don't (http://clang-developers.42468.n3.nabble.com/Variable-length-arrays-with-initialization-td4059842.html).
- VLA seems removed from C++14 (https://gcc.gnu.org/gcc-5/changes.html, https://stackoverflow.com/questions/40633344/variable-length-arrays-in-c14).

**Comment by pazeshun** [comment]
Not tested with motors yet.

**Comment by routiful** [comment]
Hi :) 
Thank you for your contribution!
However, I have got many issues as someone doesn't know how to handle `vector` library.
I know your code is right and more compatible but I think we need to find another way to initialize array simply.

**Comment by routiful** [comment]
I merged new version. please check it. thanks :)

**Pull request closed without merging**
