### PR TITLE
New methods for syncRead / syncWrite and MX protocol 2.0 devices

### PR DESCRIPTION
**Pull request by SammyRamone**
Hello,

this pull request is mainly based on the code of the fork of the TU Darmstadt (https://github.com/tu-darmstadt-ros-pkg/dynamixel-workbench). @Martin-Oehler added new methods for syncWrite and syncRead with conversion methods to directly use, for example, positions in rad rather than ticks.
I refactored the code and added a few further fixes.
Furthermore, I added a new device for the MX-108 with the new firmware version. Since the change, all registers are different, therefore the old .device file doesn't work any more.
I tested the code on a MX-108.
If there are further things to change, I am happy to provide further commits.

### CODE REVIEW

**Comment by routiful** [comment]
Hello @SammyRamone  :)

Thank you for your pull request!!
I have updated dynamixel-workbench in develop branch. It supports MX series using protocol 2.0.
You can use it soon.

Thanks
Darby

**Comment by SammyRamone** [comment]
Hi,
thank you for your response. I tried the development branch version and it works :)
I have a follow up question about the sync read. Is it planned to introduce a method to read multiple registers with one sync read? This is very useful, for example to read the current position, velocity and effort with just one packet. This reduces the number of bytes to send on the bus and therefore increases the update rate, when controlling a lot of servos.

**Comment by routiful** [comment]
Hi :)

DYNAMIXEL SDK already supports your suggestion. It's called [Bulk Read](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/sample_code/cpp_bulk_read_write_protocol_2_0/#cpp-bulk-read-write-protocol-20)

Another example using Dynamixel-Workbench, please follow this [link](https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/OpenCR/examples/08.%20DynamixelWorkbench/r_Bulk_Read_Write/r_Bulk_Read_Write.ino)

Thanks :)
Darby

**Comment by SammyRamone** [comment]
Hi :)
thanks for the quick response. I know about the Bulk read and it would be possible to use it, but the sync read is more efficient, since the packet is smaller.
All registers that I want to read are following each other, so a sync read is possible. For example to read all present currents, velocities and positions of a MX-64 I can use the following package:
ff ff fd 00 fe 1b 00 82 7e 00 0a 00 13 14 10 12 06 0c 0a 08 0e 02 04 0f 11 05 0b 09 07 0d 01 03 a5 47                                            

This reads 10 bits starting from address 126 for ids 1 to 20 (the order of the ids is a bit mixed up, but it dosn't matter). I tried this with 20 Dynamixels and it works well, I get 20 status packages with the 10 bit of information.

Comparing different approaches for Bytes send to get these 3 registers for 20 motors:
Three Sync Read for one register each: 3*34B + 2* 20 * 15B + 20*13B = 962B
Singe Bulk Read for all three registers: 1* 110B + 20*21B = 530B
Single Sync Read for all three registers: 1*34B + 20*21B = 454B

While your proposed solution is already better than 3 sync reads, a single sync read needs even less Bytes.

**Comment by SammyRamone** [comment]
Furthermore, the example that you provided also does two bulk reads to read the LED and the position.
After looking at the SDK code I also think that it is not able to read multiple registers with one packet.

**Comment by routiful** [comment]
Oh, I misunderstand your first question. Actually, we don't have any plan to develop method to read multiple registers with one sync read. But we have been concerned about it.
Thank you your inquiry. And i will suggest this issue in my team.

Best regards
Darby

**Comment by SammyRamone** [comment]
So I think you can close this pull request. Since it doesn't make sense to merge this.
I made a pull request (https://github.com/ROBOTIS-GIT/dynamixel-workbench/pull/97) with new methods for the discussed reading of multiple registers.

**Pull request closed without merging**
