### PR TITLE
modified method to call control items

### PR DESCRIPTION
**Pull request by routiful**
This PR was opened by https://github.com/ROBOTIS-GIT/dynamixel-workbench/issues/220

After updates, more flexible code supports all Dynamixels including PRO.

### CODE REVIEW

**Comment by routiful** [comment]
@kijongGil  Please review this PR.

**Comment by kijongGil** [comment]
I tested dynamixel_workbench_controllers with PRO-H54-200-S500-R. It is working for command service. But, /dynamixel_workbench/dynamixel_state topic is something wrong. This topic is not appear correctly data, just appear fixed data.

**Comment by routiful** [comment]
@kijongGil 

I fixed bug. Please check again.

**Comment by kijongGil** [comment]
@routiful 
I checked again your PR and found another problems.
First, I ran roslaunch dynamixel_workbench_controllers dynamixel_controllers.launch with basic.yaml, 'groupSyncWrite addparam failed' error occurred when I call to service /dynamixel_workbench/execution.

Second, I ran roslaunch dynamixel_workbench_controllers dynamixel_controllers.launch with wheel_2_0.yaml, It is can't find to Profile_Acceleration, Profile_Velocity.

Finally, roslaunch dynamixel_workbench_operators wheel_operator.launch is not working. This node publish /dynamixel_workbench/cmd_vel topic. But, DXL is not move.

**Comment by routiful** [comment]
@kijongGil 

I updates initSDK function and modified controller.launch file.
Please check again and feedback to me.

**Comment by kijongGil** [comment]
Ok, I checked this PR is working.
Thanks.

**Pull request merged**
