### PR TITLE
Velocity control arbitrary number of motors

### PR DESCRIPTION
**Pull request by Achllle**
Create a new way of controlling the velocity of an arbitrary numer of IDs for X and MX series

Based on velocity_control example in dynamixel_workbench

Note/issue: when launching a single dynamixel, one needs to add a comma after the id number,
otherwise getting the param will default to '1'. Seems to be a problem with node_hande.param. 

I did not provide documentation, that seems to be living in the emanual

## test
The file doesn't automatically detect the attached motors, you need to provide them.
```
roslaunch dynamixel_workbench_controllers general_velocity_control.launch ids:=1,2,3,4
```

### CODE REVIEW

**Comment by gpwhd07** [comment]
Hi @Achllle, 

I tested your code. It worked successfully.

Thank you for your contribution. 
We will consider uploading your code in the next update.



I

**Comment by THANKWOO** [comment]
Hi @Achllle 

i used your code and i found some error in my environment

ERROR: cannot launch node of type [dynamixel_workbench_controllers/general_velocity_control]: can't locate node [general_velocity_control] in package [dynamixel_workbench_controllers]

could you give me some help to handle this?
Thank you

**Comment by Achllle** [comment]
@THANKWOO Here are some things that come to mind:

* did you check out the right branch? Is the file present in the src folder of the package?
* did you catkin_make and source your workspace?

**Comment by gpwhd07** [comment]
Thank you for your helps. 
We will update dynamixel workbench.
This issue will be closed.

**Comment by Achllle** [comment]
I don't understand why this isn't merged in if you want to use it

**Comment by gpwhd07** [comment]
@Achllle, I'm sorry I did not apply your request immediately.
We have a major update plan for the Dynamixel Workbench, including your request as well as other requests.
Therefore, we can not immediately apply your request.
Your code is very useful for major updates.

**Pull request closed without merging**
